name: biodata Main

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: biodata Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Clone and build java-common-libs
#        run: cd ~ && git clone -b develop https://github.com/opencb/java-common-libs.git && cd ~/java-common-libs && mvn -T 2 clean install -DskipTests && cd $GITHUB_WORKSPACE
      - name: Maven Validate
        run: mvn validate
      - name: Maven Build (skip tests)
        run: mvn -T 2 clean install -DskipTests
  test:
    name: biodata Test
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Clone and build java-common-libs
#        run: cd ~ && git clone -b develop https://github.com/opencb/java-common-libs.git && cd ~/java-common-libs && mvn -T 2 clean install -DskipTests && cd $GITHUB_WORKSPACE
      - name: Install Samtools
        run: sudo apt-get install samtools
      - name: Build with Maven
        run: mvn -T 2 clean install
  deploy:
    name: Deploy biodata libs and Java docs
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Clone and build java-common-libs
#        run: cd ~ && git clone -b develop https://github.com/opencb/java-common-libs.git && cd ~/java-common-libs && mvn -T 2 clean install -DskipTests && cd $GITHUB_WORKSPACE
      - name: Build with Maven CLI
        run: mvn -T 2 clean install -DskipTests
      - name: Deploy to Maven Central respository
        uses: samuelmeuli/action-maven-publish@v1
        with:
          nexus_username: ${{ secrets.MAVEN_NEXUS_USER }}
          nexus_password: ${{ secrets.MAVEN_NEXUS_PASSWORD }}
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          maven_args: -DskipTests
#      - name: Get biodata version
#        id: get_version
#        run: echo ::set-output name=VERSION::2.0.0-SNAPSHOT
#      - name: Generate Javadocs
#        run: mvn javadoc:aggregate
#      - name: Deploy Javadocs
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BASE_BRANCH: next               # The branch the action should deploy from.
#          BRANCH: gh-pages                # The branch the action should deploy to.
#          FOLDER: target/site/apidocs     # The folder the action should deploy.
#          TARGET_FOLDER: apidocs/${{ steps.get_version.outputs.VERSION }}
