name: Release new biodata version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  test:
    uses: opencb/java-common-libs/.github/workflows/build-analysis.yml@develop
    needs: build
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SSH_TESTING_SERVER_HOST: ${{ secrets.SSH_TESTING_SERVER_HOST}}
      SSH_TESTING_SERVER_PORT: ${{ secrets.SSH_TESTING_SERVER_PORT}}
      SSH_TESTING_SERVER_USER: ${{ secrets.SSH_TESTING_SERVER_USER }}
      SSH_TESTING_SERVER_PASSWORD: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test
    secrets:
      MAVEN_NEXUS_USER: ${{ secrets.MAVEN_NEXUS_USER }}
      MAVEN_NEXUS_PASSWORD: ${{ secrets.MAVEN_NEXUS_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

  release:
    uses: opencb/java-common-libs/.github/workflows/release-github-workflow.yml@develop
    needs: test
