name: Push biodata develop
on:
  push:
    branches:
      - TASK-*

jobs:

  test-report:
    uses: opencb/biodata/.github/workflows/build-test.yml@TASK-2270
    with:
      sonarProjectKey: opencb_biodata
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test-report
    secrets:
      MAVEN_NEXUS_USER: ${{ secrets.MAVEN_NEXUS_USER }}
      MAVEN_NEXUS_PASSWORD: ${{ secrets.MAVEN_NEXUS_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}