name: Push biodata task

on:
  push:
    branches:
      - TASK-*

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit
    with:
      report_context: development
      report_dir: ${{ github.ref_name }}/biodata/${{ github.sha }}

