name: Build and test the project
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  test:
    name: Test and push Sonar analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Install Samtools
        run: sudo apt-get install samtools
      - name: Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify surefire-report:report --fail-never org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=opencb_biodata
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        ## Skip cancelled()
        ## https://docs.github.com/en/actions/learn-github-actions/expressions#cancelled
        if: success() || failure()
        with:
          check_name: "Surefire tests report"
          report_paths: './**/surefire-reports/TEST-*.xml'
          commit: '${{ github.sha }}'
          fail_on_test_failures: true
